blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, ReplyCommentView, AddCommentView


app_name='blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('comment/<int:comment_id>/reply/', ReplyCommentView.as_view(), name='reply_comment'),
    path('post/<slug:slug>/comment/', AddCommentView.as_view(), name='add_comment'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class BlogPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'slug': self.slug})

class Comment(models.Model):
    post = models.ForeignKey(BlogPost, related_name="comments", on_delete=models.CASCADE)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    website = models.URLField(blank=True)
    body = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    is_admin = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"Comment by {self.name}"

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'website', 'body']
        widgets = {
            'body': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Leave a comment...'}),
        }

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from .models import BlogPost, Comment
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.urls import reverse_lazy, reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.decorators import method_decorator


class BlogListView(ListView):
    model = BlogPost
    template_name = 'blog/blog_list.html'
    context_object_name = 'posts'


class BlogDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/blog_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['post'] = self.object
        context['recent_posts'] = BlogPost.objects.order_by('-created_at')[:4]
        context['top_level_comments'] = post.comments.filter(parent__isnull=True)
        return context
    

class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/blog_detail.html'

    def dispatch(self, request, *args, **kwargs):
        self.post_instance = BlogPost.objects.get(slug=self.kwargs['slug'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.post = self.post_instance
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.post_instance
        context['recent_posts'] = BlogPost.objects.order_by('-created_at')[:4]
        context['top_level_comments'] = self.post_instance.comments.filter(parent__isnull=True)
        context['form'] = self.get_form()  # in case template expects `form` (like {{ form.as_p }})
        return context

    def get_success_url(self):
        return self.post_instance.get_absolute_url()


class ReplyCommentView(LoginRequiredMixin, View):
    def post(self, request, comment_id):
        parent_comment = get_object_or_404(Comment, id=comment_id)

        if request.user.is_superuser:
            body = request.POST.get('body')
            if body:
                Comment.objects.create(
                    post=parent_comment.post,
                    parent=parent_comment,
                    name=request.user.username,
                    email=request.user.email,
                    body=body,
                    is_admin=True,
                )

                messages.success(request, "Reply posted successfully.")

        return redirect('blog:blog_detail', slug=parent_comment.post.slug)
    


    

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block layout %}


<body class="blog-post-page no-header-wrapper">
    <div class="breadcrumbs container">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{%url 'index'%}">Home</a></li>
            <li class="breadcrumb-item"><a href="{%url 'blog:blog_list'%}">Blog</a></li>
            <li class="active breadcrumb-item">Extramile Plus</li>
        </ul>
    </div><!--//breadcrumbs-->

    <!-- ******Blog Post****** -->
    <div class="blog-post-wrapper container">
        <div class="row gx-5">
            <div class="blog-entry col-lg-8 col-12">
                <article class="post">
                    <h2 class="title">{{ post.title }}</h2>
                    <div class="meta">
                        <ul class="meta-list list-inline">
                            <li class="list-inline-item post-time post_date date updated">
                                <i class="fas fa-calendar"></i> {{ post.pub_date|date:"d M," }}
                            </li>
                            <li class="list-inline-item post-author">
                                <i class="fas fa-user"></i>
                                <a class="text-link" href="#">{{ post.author.get_full_name }}</a>
                            </li>
                            <li class="list-inline-item post-comments-link">
                                <a class="text-link" href="#comment-area">
                                    <i class="fas fa-comments"></i>{{ post.comments.count }} Comments
                                </a>
                            </li>
                        </ul><!--//meta-list-->
                    </div><!--meta-->
                    <div class="content">
                        <p class="post-figure">
                            {% if post.image %}
                            <img class="img-fluid post-image" src="{{ post.image.url }}" alt="{{ post.title }}">
                            {% else %}
                            <img class="img-fluid post-image" src="{% static 'assets/images/blog/blog-1.jpg' %}"
                                alt="Default Image">
                            {% endif %}
                        </p>

                        {{ post.content|safe }}


                        <p class="video-container ratio ratio-16x9 mt-5">
                            <iframe src="//player.vimeo.com/video/81676731?color=ffffff&amp;wmode=transparent"
                                width="720" height="405" frameborder="0" webkitallowfullscreen mozallowfullscreen
                                allowfullscreen></iframe>
                        </p>
                    </div>

                    <nav class="post-nav">
                        {% if previous_post %}
                        <span class="nav-previous"><a href="{% url 'blog_detail' previous_post.pk %}" rel="prev"><i
                                    class="fas fa-long-arrow-alt-left"></i>Previous</a></span>
                        {% endif %}
                        {% if next_post %}
                        <span class="nav-next"><a href="{% url 'blog_detail' next_post.pk %}" rel="next">Next<i
                                    class="fas fa-long-arrow-alt-right"></i></a></span>
                        {% endif %}
                    </nav><!--//post-nav-->

                    <div id="comment-area" class="comment-area">
                        <div class="comment-container">
                            <div class="comment-list">
                                <h3 class="title">{{ post.comments.count }} Comment{{ post.comments.count|pluralize }}</h3>
                        
                                {% for comment in top_level_comments %}
                                <div class="comment-item depth-1 parent">
                                    <div class="comment-item-box rounded">
                                        <!-- <div class="comment-author">
                                            <img class="img-fluid" src="{% static 'assets/images/comment/user-1.jpg' %}" alt="{{ comment.name }}" />
                                        </div> -->
                                        <div class="comment-body">
                                            <cite class="name">{{ comment.name }} Says:</cite>
                                            <p class="time">{{ comment.created_at|date:"M d, \\a\\t g:ia" }}</p>
                                            <div class="content">
                                                <p>{{ comment.body }}</p>
                                            </div>
                                        </div>
                                    </div>
                        
                                    {% for reply in comment.replies.all %}
                                    <div class="comment-item depth-2 reply ms-5 mt-3">
                                        <div class="comment-item-box rounded bg-light">
                                            <!-- <div class="comment-author">
                                                <img class="img-fluid" src="{% static 'assets/images/comment/user-1.jpg' %}" alt="{{ reply.name }}" />
                                            </div> -->
                                            <div class="comment-body">
                                                <cite class="name">{{ reply.name }} (Admin)</cite>
                                                <p class="time">{{ reply.created_at|date:"M d, \\a\\t g:ia" }}</p>
                                                <div class="content">
                                                    <p>{{ reply.body }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                        
                                    {% if request.user.is_superuser %}
                                    <!-- Admin Reply Form -->
                                    <div class="reply-form mt-3 ms-5">
                                        <form method="post" action="{% url 'blog:reply_comment' comment.id %}">
                                            {% csrf_token %}
                                            <div class="mb-2">
                                                <textarea name="body" rows="3" class="form-control" placeholder="Write a reply..." required></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-sm btn-primary">Reply</button>
                                        </form>
                                    </div>
                                    {% endif %}
                                </div>
                                {% empty %}
                                <p>No comments yet. Be the first to comment!</p>
                                {% endfor %}
                            </div>
                        </div>
                        

                        <div class="comment-form-container">
                            <h3 class="title">Leave a comment</h3>
                            <form id="comment-form" class="comment-form form" method="post"
                                action="{% url 'blog:add_comment' post.slug %}">
                                {% csrf_token %}
                                <div class="row g-3">
                                    <div class="col-md-6 col-12">
                                        <label class="sr-only" for="cname">Name</label>
                                        <input type="text" class="form-control" id="cname" name="name"
                                            placeholder="Name" minlength="2" required>
                                    </div>
                                    <div class="col-md-6 col-12 ">
                                        <label class="sr-only" for="cemail">Email</label>
                                        <input type="email" class="form-control" id="cemail" name="email"
                                            placeholder="Email" required>
                                    </div>
                                    <div class="col-12 ">
                                        <label class="sr-only" for="cwebsite">Website</label>
                                        <input type="url" class="form-control" id="cwebsite" name="website"
                                            placeholder="Website">
                                    </div>
                                    <div class="col-12 ">
                                        <label class="sr-only" for="ccomment">Leave a Comment</label>
                                        <textarea class="form-control" id="ccomment" name="body"
                                            placeholder="Leave your comment" rows="12" required></textarea>
                                    </div>
                                    <div class="col-12 ">
                                        <button type="submit" class="btn btn-cta btn-cta-secondary">Submit
                                            Comment</button>
                                    </div>
                                </div><!--//row-->
                            </form><!--//contact-form-->
                        </div>

                    </div>

                </article><!--//post-->
            </div><!--//blog-entry-->


            <aside id="blog-sidebar" class="blog-sidebar col-lg-4  col-12  ms-lg-auto">
                <section class="widget search">
                    <h3 class="sr-only title">Search Blog</h3>
                    <form class="search-blog-form row g-1">
                        <div class="col-auto">
                            <input type="text" class="form-control" placeholder="Search blog...">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-cta btn-cta-secondary"><i
                                    class="fas fa-search"></i></button>
                        </div>
                    </form>
                </section><!--//search-->
                <section class="widget recent-posts">
                    <h3 class="title">Recent Posts</h3>
                    <ul class="list-unstyled">
                        {% for post in recent_posts %}
                        <li>
                            <img class="thumb img-fluid" src="{{ post.image.url|default:'path/to/default/image.jpg' }}" alt="{{ post.title }}" />
                            <span class="post-info">
                                <a class="post-title" href="{% url 'blog:blog_detail' post.slug %}">{{ post.title }}</a><br />
                                <span class="date">{{ post.created_at|date:"d M" }}</span>
                            </span>
                        </li>
                        {% endfor %}
                    </ul>
                </section>

                <section class="widget categories">
                    <h3 class="title">Categories</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">News</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">UX Design</a></li>
                        <li><a href="#">Freebies</a></li>
                    </ul>
                </section><!--//widget-->
                <section class="widget archives">
                    <h3 class="title">Archives</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">2023 </a><span class="count">(2)</span></li>
                        <li><a href="#">2022 </a><span class="count">(12)</span></li>
                        <li><a href="#">2021 </a><span class="count">(6)</span></li>
                    </ul>
                </section><!--//widget-->

            </aside><!--//blog-side-bar-->
        </div><!--//row-->
    </div><!--//blog-->

    {% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html" %}
{%load static%}
{% block title %}Blog{% endblock %}
{% block layout %}


<body class="blog-home-page">   
    <div class="header-wrapper header-wrapper-blog-home"> 
        <section class="promo section">
            <div class="container text-center">                
                <h2 class="title">Blog</h2>
                <p class="intro">Lorem ipsum dolor sit amet consectetuer adipiscing elit massa sociis natoque penatibus et magnis dis parturient montes</p>
            </div><!--//container-->
        </section><!--//promo-->
    </div><!--//header-wrapper-->
       
    <!-- ******Blog list Section****** -->
    <section id="blog-list" class="blog-list section">
        <div class="container">
            {% for post in posts %}
            <article class="item">                  
                <div class="row">
                    <h3 class="post-title col-lg-10 col-md-9 col-12 ms-md-auto">
                        <a href="{% url 'blog:blog_detail' slug=post.slug %}">
                            {{ post.title }}
                        </a>
                    </h3>
                    <div class="w-100"></div>
                    <div class="meta col-lg-2 col-md-3 col-12 text-right">
                        <ul class="meta-list list-unstyled">                                       
                            <li class="post-time post_date date updated rounded">
                                <span class="date">{{ post.pub_date|date:"d" }}</span>
                                <span class="month">{{ post.pub_date|date:"M" }}</span>
                            </li>
                            <li class="post-author">
                                <a href="#">{{ post.author.get_full_name|default:"Admin" }}</a>
                            </li>
                            <li class="post-comments-link">
                                Comments: <a href="{% url 'blog:blog_detail' slug=post.slug %}#comment-area">
                                    {{ post.comments.count|default:"0" }}
                                </a>
                            </li>
                        </ul>                       	
                    </div>                  
                    <div class="content-wrapper col-lg-10 col-md-9 col-12">
                        <!-- changed this part -->
                        <figure class="figure" style="height: 300px;">
                            <img src="{{ post.image.url }}" class="img-fluid w-100 h-100 object-fit-cover" alt="{{ post.title }}">
                        </figure>
                        
                        <div class="content">
                            <div class="desc">
                                <p>{{ post.content|truncatechars:200 }}</p>
                                <a class="text-link" href="{% url 'blog:blog_detail' slug=post.slug %}">
                                    Read more <i class="fas fa-long-arrow-alt-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>  
                </div>
            </article>
            {% endfor %}
            
                <div class="pagination-container text-center">
                    <ul class="pagination justify-content-center">
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        <li class="page-item active"><a class="page-link" href="#">1<span class="sr-only">(current)</span></a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                        <li class="page-item"><a class="page-link" href="#">5</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul><!--//pagination-->
                </div><!--//pagination-container-->       
            </article><!--//item-->
        </div><!--//container-->
    </section><!--//blog-list--> 
</body>


{%endblock%}